# Generated by Django 5.2.5 on 2025-08-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_price', models.PositiveIntegerField(default=1000)),
                ('max_bet_value', models.CharField(max_length=20)),
                ('players', models.PositiveIntegerField(default=0)),
                ('max_players', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('see', 'See'), ('pack', 'Pack'), ('slide', 'Slide')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='cashmastertable.gametable')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_position', models.PositiveIntegerField()),
                ('is_waiting', models.BooleanField(default=True)),
                ('is_current_turn', models.BooleanField(default=False)),
                ('game_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmastertable.gametable')),
            ],
        ),
    ]
