# Generated by Django 5.2.5 on 2025-08-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashmastertable', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTable',
            new_name='MasterGameTable',
        ),
    ]
