# Generated by Django 5.2.5 on 2025-09-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmastertable', '0003_rename_gametable_mastergametable'),
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='master_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_tables', to='cashmastertable.mastergametable'),
        ),
    ]
