# Generated by Django 5.2.5 on 2025-09-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gametable_master_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametable',
            old_name='master_table',
            new_name='game_master_table',
        ),
    ]
