# Generated by Django 5.2.5 on 2025-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_master_table_gametable_game_master_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametable',
            name='game_master_table',
        ),
    ]
