# Generated by Django 5.2.5 on 2025-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gametable_game_master_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='boot_price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gametable',
            name='max_bet_value',
            field=models.CharField(default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='gametable',
            name='max_players',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
