# Generated by Django 5.2.4 on 2025-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gametable_boot_price_gametable_max_bet_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCard',
            fields=[
                ('master_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('suit', models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('spades', 'Spades'), ('clubs', 'Clubs')], max_length=10)),
                ('rank', models.CharField(choices=[('A', 'Ace'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King')], max_length=5)),
                ('image', models.ImageField(upload_to='cards/')),
            ],
        ),
    ]
