# Generated by Django 5.2.4 on 2025-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_mastercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
