# Generated by Django 5.2.4 on 2025-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='distributed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
